import {
  PLAN_SETUP,
  ALTORIA,
  CUBE_PLANET,
  BISCAYNE_VR,
  MELTING,
  ENERGY_USE,
  THE_COLORING_BOOK,
  HAPTICS_SIMULATOR,
  INCIDENTCARE,
  POLICE_RADIO_APP,
  TRIANGO,
  EAT_GREEN_STAY_COOL,
  THEME_PARK_TICKET_APP
} from '../posts/index';

export const projects = [
  PLAN_SETUP,
  ALTORIA,
  CUBE_PLANET,
  BISCAYNE_VR,
  MELTING,
  ENERGY_USE,
  THE_COLORING_BOOK,
  HAPTICS_SIMULATOR,
  INCIDENTCARE,
  POLICE_RADIO_APP,
  TRIANGO,
  EAT_GREEN_STAY_COOL,
  THEME_PARK_TICKET_APP
];
